[phases.setup]
nixpkgsArchive = 'e89cf1c932006531f454de7d652163a9a5c86668'

[phases.build]
cmds = [
    'bunx prisma migrate deploy',
    'bunx prisma generate',
    'ln -s /usr/lib/x86_64-linux-gnu/libssl.so /lib/libssl.so',
    'ln -s /usr/lib/x86_64-linux-gnu/libssl.so.3 /lib/libssl.so.3',
    'ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so /lib/libcrypto.so',
    'ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.3 /lib/libcrypto.so.3',
]

[start]
cmd = 'bun --bun run start'